import { NextResponse } from "next/server";
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { join } from "node:path";

/**
 * POST /api/setup/save
 * Writes env vars to .env file during local first-time setup.
 * Only works when:
 * 1. Running locally (not on Vercel)
 * 2. MCP_AUTH_TOKEN is not yet set (first-time setup)
 */
export async function POST(request: Request) {
  // Block on Vercel — env vars must be set via dashboard there
  if (process.env.VERCEL) {
    return NextResponse.json(
      {
        error:
          "Cannot write .env on Vercel. Use the Vercel dashboard to set environment variables.",
      },
      { status: 403 }
    );
  }

  // Block if already configured (security: prevent overwriting existing config)
  if (process.env.MCP_AUTH_TOKEN) {
    return NextResponse.json(
      { error: "Server is already configured. Delete .env and restart to reconfigure." },
      { status: 403 }
    );
  }

  const body = (await request.json()) as { envVars: Record<string, string> };
  if (!body.envVars || typeof body.envVars !== "object") {
    return NextResponse.json({ error: "Missing envVars object" }, { status: 400 });
  }

  const projectRoot = process.cwd();
  const envPath = join(projectRoot, ".env");
  const envExamplePath = join(projectRoot, ".env.example");

  let envContent = "# MyMCP — Generated by Setup Wizard\n";
  envContent += `# Created: ${new Date().toISOString().split("T")[0]}\n\n`;

  const writtenVars = new Set<string>();

  // Use .env.example as template if it exists
  if (existsSync(envExamplePath)) {
    const example = readFileSync(envExamplePath, "utf-8");
    const lines = example.split("\n");
    for (const line of lines) {
      const match = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
      if (match && body.envVars[match[1]] !== undefined) {
        envContent += `${match[1]}=${body.envVars[match[1]]}\n`;
        writtenVars.add(match[1]);
      } else {
        envContent += line + "\n";
      }
    }
  }

  // Append any remaining vars
  for (const [key, value] of Object.entries(body.envVars)) {
    if (!writtenVars.has(key)) {
      envContent += `${key}=${value}\n`;
    }
  }

  writeFileSync(envPath, envContent);

  return NextResponse.json({
    ok: true,
    message: ".env saved. Restart the dev server to apply changes.",
    path: envPath,
  });
}
